---
# tasks file for dotfiles
- name: Check if dotfiles directory exsists
  stat:
    path: "{{ dotfiles['dest'] }}"
  register: dest_data

- name: Update dotifles
  git:
    repo: "{{ dotfiles.repo }}"
    dest: "~/{{ dotfiles.dest }}"
    bare: true
    update: true

- name: Install dotfiles
  include_tasks:
    file: install.yml
  when: dest_data['stat']['exists'] == false
